export const BUSINESS_CATEGORIES: string[] = [
  'Accounting & Tax',
  'Advertising',
  'Animal Hospitals',
  'Apparel & Clothing',
  'Attorneys',
  'Auto Repair',
  'Bakeries & Cafes',
  'Banks',
  'Barbershops',
  'Bars & Nightlife',
  'Beauty Salons',
  'Business Consulting',
  'Car Dealerships',
  'Car Wash',
  'Catering',
  'Childcare',
  'Chiropractors',
  'Cleaning Services',
  'Construction',
  'Daycare Centers',
  'Dental Clinics',
  'Digital Marketing',
  'Doctors & Physicians',
  'Dry Cleaning',
  'Education & Tutoring',
  'Electrical Services',
  'Electronics Repair',
  'Engineering',
  'Event Planning',
  'Family Law',
  'Fashion Retail',
  'Financial Planning',
  'Fitness Centers',
  'Flooring',
  'Florists',
  'Food Trucks',
  'General Contractors',
  'Graphic Design',
  'Grocery Stores',
  'Gyms & Studios',
  'Hair Salons',
  'HVAC (Heating & Air)',
  'Home Decor',
  'Home Health Care',
  'Hotels & Lodging',
  'Insurance Agencies',
  'Interior Design',
  'Investment Services',
  'IT Support & Managed Services',
  'Janitorial Services',
  'Jewelry Stores',
  'Junk Removal',
  'Kitchen Remodeling',
  'Krav Maga & Martial Arts',
  'Landscaping',
  'Laundromats',
  'Law Firms',
  'Library & Community Centers',
  'Locksmiths',
  'Marketing Agencies',
  'Massage Therapy',
  'Mechanics',
  'Medical Clinics',
  'Mental Health',
  'Mortgages',
  'Nail Salons',
  'Non-Profit Organizations',
  'Nursing Homes',
  'Office Supplies',
  'Optometrists',
  'Orthodontists',
  'Painting',
  'Personal Injury Law',
  'Pest Control',
  'Pet Stores',
  'Pharmacies',
  'Photography',
  'Plumbing',
  'Quick-Service Restaurants',
  'Real Estate Agencies',
  'Reconstruction',
  'Religious Centers',
  'Restaurants',
  'Roofing',
  'Schools & Colleges',
  'Security Systems',
  'SEO Services',
  'Shipping & Logistics',
  'Solar Energy',
  'Spas',
  'Tattoo & Piercing',
  'Tax Preparation',
  'Tech Support',
  'Therapy',
  'Tire Shops',
  'Towing',
  'Travel Agencies',
  'Urgent Care Services',
  'Upholstery & Furniture Repair',
  'Veterinary Services',
  'Video Production',
  'Virtual Assistants',
  'Web Development',
  'Wedding Venues',
  'Weight Loss Centers',
  'Window Cleaning',
  'X-Ray & Imaging Centers',
  'Yoga Studios',
  'Youth Organizations',
  'Zero-Waste Shops',
  'Zoological Services',
];

const CATEGORY_ALIASES: Record<string, string> = {
  electrical: 'Electrical Services',
  'electrical service': 'Electrical Services',
  'electrical services': 'Electrical Services',
  electrician: 'Electrical Services',
  cleaning: 'Cleaning Services',
  'cleaning service': 'Cleaning Services',
  'cleaning services': 'Cleaning Services',
  hvac: 'HVAC (Heating & Air)',
  'hvac services': 'HVAC (Heating & Air)',
  tech: 'Tech Support',
  'tech services': 'Tech Support',
};

export const normalizeCategory = (category: string) => {
  const value = String(category || '').trim();
  if (!value) return '';

  const canonical = CATEGORY_ALIASES[value.toLowerCase()];
  if (canonical) return canonical;

  return value;
};

export const ALL_CATEGORIES_WITH_DEFAULT = ['All Categories', ...BUSINESS_CATEGORIES];
